SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS operators;


SET default_tablespace = '';

CREATE TABLE operators.deliveries (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    download_report_url character varying(1000),
    is_active boolean NOT NULL,
    manager_code bigint NOT NULL,
    municipality_code character varying(10) NOT NULL,
    observations character varying(500) NOT NULL,
    operator_id bigint NOT NULL
);

ALTER TABLE operators.deliveries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME operators.deliveries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE operators.operators (
    id bigint NOT NULL,
    alias character varying(20),
    created_at timestamp without time zone NOT NULL,
    is_public boolean,
    name character varying(255) NOT NULL,
    tax_identification_number character varying(255) NOT NULL,
    operator_state_id bigint NOT NULL
);

ALTER TABLE operators.operators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME operators.operators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE operators.operators_states (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE operators.operators_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME operators.operators_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE operators.operators_users (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    user_code bigint NOT NULL,
    operator_id bigint NOT NULL
);

ALTER TABLE operators.operators_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME operators.operators_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE operators.supplies_delivered (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    download_report_url character varying(1000),
    downloaded boolean NOT NULL,
    downloaded_at timestamp without time zone,
    downloaded_by bigint,
    observations character varying(500),
    supply_code bigint NOT NULL,
    delivery_id bigint NOT NULL
);

ALTER TABLE operators.supplies_delivered ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME operators.supplies_delivered_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

INSERT INTO operators.operators_states VALUES (1, 'ACTIVO');
INSERT INTO operators.operators_states VALUES (2, 'INACTIVO');

SELECT pg_catalog.setval('operators.deliveries_id_seq', 1, false);
SELECT pg_catalog.setval('operators.operators_id_seq', 1, false);
SELECT pg_catalog.setval('operators.operators_states_id_seq', 2, true);
SELECT pg_catalog.setval('operators.operators_users_id_seq', 1, false);
SELECT pg_catalog.setval('operators.supplies_delivered_id_seq', 1, false);

ALTER TABLE ONLY operators.deliveries
    ADD CONSTRAINT deliveries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY operators.operators
    ADD CONSTRAINT operators_pkey PRIMARY KEY (id);

ALTER TABLE ONLY operators.operators_states
    ADD CONSTRAINT operators_states_pkey PRIMARY KEY (id);

ALTER TABLE ONLY operators.operators_users
    ADD CONSTRAINT operators_users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY operators.supplies_delivered
    ADD CONSTRAINT supplies_delivered_pkey PRIMARY KEY (id);

ALTER TABLE ONLY operators.supplies_delivered
    ADD CONSTRAINT fk2ncpuoqqwylr1kqucgr50qo7v FOREIGN KEY (delivery_id) REFERENCES operators.deliveries(id);

ALTER TABLE ONLY operators.deliveries
    ADD CONSTRAINT fk7y1de51e1guer6w1le5dxihf0 FOREIGN KEY (operator_id) REFERENCES operators.operators(id);

ALTER TABLE ONLY operators.operators_users
    ADD CONSTRAINT fk9rj5yw8f3rw8wfx89mwq0yqe9 FOREIGN KEY (operator_id) REFERENCES operators.operators(id);

ALTER TABLE ONLY operators.operators
    ADD CONSTRAINT fkdkichydjv0g7r2dox2dxkdbik FOREIGN KEY (operator_state_id) REFERENCES operators.operators_states(id);